# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15a70ae912cad9534b49e450be0d884773acdfa4c67e054fc9d75345cf15ce742a6bc16c90d47ec9708838ea5d02536a453a5e9164ec239d36c0142cca1a52ea

test:
  secret_key_base: 81dccfd3f266d4e8ad80200571bc376c970f234c9a96883054e4e8b8edbbac4b7059ba86cb080a615827af1df602b79b24a1e9a95b54df768e9e32b1a78b414c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
